### ISSUE TITLE
添加本人项目OpenLuckyRandom请求

### ISSUE THREAD

**Issue by WhatDamon** [Awesome-Iwb/Awesome-Iwb#3]
仓库地址：https://github.com/WhatDamon/OpenLuckyRandom
技术栈：C#、OpenCvSharp4等
许可证：Apache 2.0

本项目是对希沃新机器自带程序LuckyRandom的开源实现，适用于希沃老设备或者鸿合一体机等

_分类：教学辅助类_

**Comment by Aris-Offline** [comment]
可以麻烦提供一下项目的简要介绍和banner吗？我最近时间比较少可能没时间上手体验项目

**Comment by WhatDamon** [comment]
https://github.com/WhatDamon/OpenLuckyRandom/blob/d1a5b47f4ee0fc38a54905b508b1f191ecba9048/README.md?plain=1#L16-L20

无banner，勋章可以从README.md中复制

**Comment by WhatDamon** [comment]
## 暂缓请求
经过实机测试BUG太多，后续有计划进行部分甚至完全重写

**Comment by Aris-Offline** [comment]
先关闭，随时可以Reopen

**Comment by dubi906w** [comment]
已添加（抱歉，我没看到这个issue😂），内容有需要添加或修改的吗？

**Comment by dubi906w** [comment]
由于该 issue 过久未活跃，已关闭。欢迎随时开启。
